### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'iter_fields' on memory game

### ISSUE THREAD

**Issue by raddevon** [johnwheeler/flask-ask#12]
Trying out the memory game example from [your AWS blog post](https://developer.amazon.com/public/community/post/Tx14R0IYYGH3SKT/Flask-Ask-A-New-Python-Framework-for-Rapid-Alexa-Skills-Kit-Development), but I'm getting an exception:

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask_ask/core.py", line 144, in _flask_view_func
    result = self._launch_view_func()
  File "/Users/raddevon/Documents/projects/alexa-tutorial/memory_game.py", line 12, in new_game
    welcome_msg = render_template('welcome')
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 553, in compile
    source = optimize(source, self)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/optimizer.py", line 27, in optimize
    return optimizer.visit(node)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/visitor.py", line 39, in visit
    return self.generic_visit(node, *args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/visitor.py", line 59, in generic_visit
    for field, old_value in node.iter_fields():
AttributeError: 'NoneType' object has no attribute 'iter_fields'
```

Can you help? I was running Python 2.7.11 and through that might be the problem, so I switched to 3.5.1. I'm getting the same exception there as before.

**Comment by johnwheeler** [comment]
Hi! Did you paste in the template code into a file called `templates.yaml`

**Comment by raddevon** [comment]
Thank you for your help, @johnwheeler. I was close. I had named it `templates.yml` instead of `templates.yaml`. 😵

Now, I'm getting `AttributeError: 'YamlLoader' object has no attribute 'last_mtime'`. Should I open a new issue?

**Comment by johnwheeler** [comment]
Bingo - that's a bug. 

FYI: 
I've been meaning to do a few things here:

1. Allow you to specify your own template file
1. Allow you to specify multiple template files in conjunction with jinja's PrefixLoader
1. The default should be templates.yaml but template.yml should work too

Yes, if you would please open a new issue. Thank you so much.
