### ISSUE TITLE
Audio issues getting INTERNAL SERVER ERROR (500)

### ISSUE THREAD

**Issue by skgali** [johnwheeler/flask-ask#126]
I am trying to run the sample as listed here: https://github.com/johnwheeler/flask-ask/tree/master/samples/audio/simple_demo
I ran the non-audio examples in there and they worked good, but not the audio sample.
While configuring in AWS, I did set the "Skill Information" to use "Audio Player" (i.e Does this skill use the audio player directives? Yes).
The copied the same code as listed in the "simple_demo" (using ngrok on my windows x64 machine).
![image](https://cloud.githubusercontent.com/assets/17819146/25567054/8e1f8f26-2db3-11e7-80a5-78bbe688c272.png)

Below is the stack trace from python script

C:\apps\Python\Python36-32\python.exe C:/apps/PycharmProjects/TestProj/Alexa/ask_audio.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 207-945-196
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2017 18:58:52] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\apps\Python\Python36-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask_ask\core.py", line 594, in _flask_view_func
    result = self._map_intent_to_view_func(self.request.intent)()
  File "C:\apps\PycharmProjects\TestProj\Alexa\ask_audio.py", line 26, in demo
    return audio(speech).play(stream_url, offset=93000)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask_ask\models.py", line 154, i play
    directive['audioItem'] = self._audio_item(stream_url=stream_url, offset=offset)
  File "C:\apps\Python\Python36-32\lib\site-packages\flask_ask\models.py", line 208, in _audio_item
    push_stream(stream_cache, context['System']['user']['userId'], stream)
  File "C:\apps\Python\Python36-32\lib\site-packages\werkzeug\local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
TypeError: 'NoneType' object is not subscriptable

During my testing of the skill, in AWS console... when I enter "begin demo", below is the **service request** json:
{
  "session": {
    "sessionId": "SessionId.5a620bab-539c-42f7-b3a0-7ad67862a01d",
    "application": {
      "applicationId": "amzn1.ask.skill.41a5e218-82cf-41ae-b6f5-6ffbe863a570"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AHU4KOJCDEQLMXFZD7HP47D2YPJ77EB3XRMVEZSDYIWVLUKUGIIFK4E6IPOZSLLFKH7U6TLXGA2NCS4H6XBXDYKHOJXP74FXEBZCOCNNKHUNPSDUNHH2UIKQYYWR6QHHWUSULF456LGX3B4L4TWC4E5GIUULO7RU52UWXFHYHUQHC7HYBRQFDLQTNOQ77RJBTTP7YB4RVIHC6YY"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.97d52191-40b3-486b-976a-d15f832711de",
    "locale": "en-US",
    "timestamp": "2017-04-30T18:46:34Z",
    "intent": {
      "name": "DemoIntent",
      "slots": {}
    }
  },
  "version": "1.0"
}
And below is the **service response** :
There was an error calling the remote endpoint, which returned HTTP 500 : INTERNAL SERVER ERROR
Appreciate your help in identifying the underlying issue.

**Comment by voutilad** [comment]
Flask-Ask should definitely handle a request without the user context a bit nicer than an HTTP 500. I can look at this later this week. Ultimately, we can let `play` directives occur cleanly...but proper handling of other AudioDirectives may just need to produce more descriptive errors.

In the mean time, @skgali please explicitly add a Context to your request. When you test using Amazon's Service Simulator UI it does not actually provide a Context element automatically. In fact, they currently claim they don't support testing AudioDirectives using the Service Simulator itself:

> **Note:** Service Simulator does not currently support testing audio player directives and customer account linking.

Until this is resolved, please try adding a valid Context. End users of the skill will always generate a Context since it's the only user-identifiable information guaranteed in every request. I don't know why Amazon's test tool doesn't provide one because [per their own documentation](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference#context-object):

> The context object provides your skill with information about the current state of the Alexa service and device at the time the request is sent to your service. This is included on all requests.

**Comment by skgali** [comment]
Thanks Dave, you guessed right.... when I passed the context, I didn't get the Internal server any more....
Here are my observations
1. When I passed the type: LaunchRequest as follows, I got the valid response
**Request**:

{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "SessionId.c137735c-f456-406a-ae72-a102cd5b53be",
    "application": {
      "applicationId": "amzn1.ask.skill.41a5e218-82cf-41ae-b6f5-6ffbe863a570"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AHU4KOJCDEQLMXFZD7HP47D2YPJ77EB3XRMVEZSDYIWVLUKUGIIFK4E6IPOZSLLFKH7U6TLXGA2NCS4H6XBXDYKHOJXP74FXEBZCOCNNKHUNPSDUNHH2UIKQYYWR6QHHWUSULF456LGX3B4L4TWC4E5GIUULO7RU52UWXFHYHUQHC7HYBRQFDLQTNOQ77RJBTTP7YB4RVIHC6YY"
    }
  },
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.41a5e218-82cf-41ae-b6f5-6ffbe863a570"
      },
      "user": {
        "userId": "amzn1.ask.account.AHU4KOJCDEQLMXFZD7HP47D2YPJ77EB3XRMVEZSDYIWVLUKUGIIFK4E6IPOZSLLFKH7U6TLXGA2NCS4H6XBXDYKHOJXP74FXEBZCOCNNKHUNPSDUNHH2UIKQYYWR6QHHWUSULF456LGX3B4L4TWC4E5GIUULO7RU52UWXFHYHUQHC7HYBRQFDLQTNOQ77RJBTTP7YB4RVIHC6YY"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      }
    },
    "AudioPlayer": {
      "offsetInMilliseconds": 0,
      "playerActivity": "IDLE"
    }
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "amzn1.echo-api.request.0000000-0000-0000-0000-00000000000",
    "timestamp": "2017-04-30T19:40:56Z",
    "locale": "string"
  }
}
**Response**:
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Welcome to an audio example. You can ask to begin demo, or try asking me to play the sax."
    },
    "card": {
      "content": "Welcome to an audio example. You can ask to begin demo, or try asking me to play the sax.",
      "title": "Audio Example",
      "type": "Simple"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "PlainText",
        "text": "You can ask to begin demo, or try asking me to play the sax."
      }
    },
    "shouldEndSession": false
  },
  "sessionAttributes": {}
}

2. When I passed the type: IntentRequest, that's where I was getting the Internal server error. Here is my JSON **request**:
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "SessionId.c137735c-f456-406a-ae72-a102cd5b53be",
    "application": {
      "applicationId": "amzn1.ask.skill.41a5e218-82cf-41ae-b6f5-6ffbe863a570"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AHU4KOJCDEQLMXFZD7HP47D2YPJ77EB3XRMVEZSDYIWVLUKUGIIFK4E6IPOZSLLFKH7U6TLXGA2NCS4H6XBXDYKHOJXP74FXEBZCOCNNKHUNPSDUNHH2UIKQYYWR6QHHWUSULF456LGX3B4L4TWC4E5GIUULO7RU52UWXFHYHUQHC7HYBRQFDLQTNOQ77RJBTTP7YB4RVIHC6YY"
    }
  },
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.41a5e218-82cf-41ae-b6f5-6ffbe863a570"
      },
      "user": {
        "userId": "amzn1.ask.account.AHU4KOJCDEQLMXFZD7HP47D2YPJ77EB3XRMVEZSDYIWVLUKUGIIFK4E6IPOZSLLFKH7U6TLXGA2NCS4H6XBXDYKHOJXP74FXEBZCOCNNKHUNPSDUNHH2UIKQYYWR6QHHWUSULF456LGX3B4L4TWC4E5GIUULO7RU52UWXFHYHUQHC7HYBRQFDLQTNOQ77RJBTTP7YB4RVIHC6YY"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      }
    },
    "AudioPlayer": {
      "offsetInMilliseconds": 0,
      "playerActivity": "IDLE"
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "amzn1.echo-api.request.0000000-0000-0000-0000-00000000000",
    "timestamp": "2017-04-30T19:06:53Z",
    "intent": {
      "name": "DemoIntent",
      "slots": {}
    },
    "locale": "string"
  }
}
Then, I felt, it may be due to the audio() command, so in the code, I commented out the audio() function and replaced with question(speech) as follows:

@ask.intent('DemoIntent')
def demo():
    speech = "Here's one of my favorites"
    stream_url = 'https://www.vintagecomputermusic.com/mp3/s2t9_Computer_Speech_Demonstration.mp3'
    return question(speech) #audio(speech).play(stream_url, offset=93000)


Now when I pass the same JSON, it returned with valid **response** as follows:
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Here's one of my favorites"
    },
    "card": null,
    "reprompt": null,
    "shouldEndSession": false
  },
  "sessionAttributes": {}
}

So it seems like there is some issue with running the audio() ?

**Comment by voutilad** [comment]
Correct! The issue you helped find is building an `audio()` response without the presence of a valid context.

The design challenge with audio controls is managing the state of which user is playing which audio stream. Recently we added the feature to properly track this information in a cache under the assumption we use the `userId` in the context as the key. When handling audio related intents, Flask-Ask tries to get the `userId` from the context to do a cache lookup or update.

Without a context, that currently fails because of an unchecked lookup of that `userId` in the non-existant context.

Any intent that doesn't try to build an `audio()` response should work fine since they don't automatically use this user-based caching.

As some background, the reason this caching is needed is Amazon/Alexa expects to close the Session when the stream begins playing. This means any session attributes you try to use for retaining stateful information are inaccessible when the user then interacts with the stream via a stop/pause, next, etc. audio directive.

**Comment by skgali** [comment]
so, is there any way to get the sample "simple-demo" code working? Any work around?

**Comment by skgali** [comment]
ok, like you said, the issue playing the audio is in the Test simulator... but it is now working on my Alexa echo dot. Earlier, it didn't work on my echo dot as well, only change I see is that I had python 3.6 then, but changed to python v2.7. I will have to confirm if this is truely an issue with python v3.6

**Comment by skgali** [comment]
Awesome! Thanks

**Comment by geekykaddy** [comment]
I faced the same problem. This thread of discussion has really helped me. I am able to play the song using my echo dot. thank you @skgali @voutilad
