### ISSUE TITLE
AttributeError: 'YamlLoader' object has no attribute 'last_mtime'

### ISSUE THREAD

**Issue by raddevon** [johnwheeler/flask-ask#14]
Now that I've named the `templates.yaml` file correctly, I'm getting this error when I hit the memory game skill's endpoint:

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask_ask/core.py", line 144, in _flask_view_func
    result = self._launch_view_func()
  File "/Users/raddevon/Documents/projects/alexa-tutorial/memory_game.py", line 21, in new_game
    welcome_msg = render_template('welcome')
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask/templating.py", line 82, in _get_source_fast
    return loader.get_source(environment, template)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/jinja2/loaders.py", line 396, in get_source
    return loader.get_source(environment, template)
  File "/usr/local/var/pyenv/versions/3.5.1/envs/alexa-tutorial/lib/python3.5/site-packages/flask_ask/core.py", line 209, in get_source
    if self.last_mtime != os.path.getmtime(self.path):
AttributeError: 'YamlLoader' object has no attribute 'last_mtime'
```

**Comment by johnwheeler** [comment]
Is this what happens when you try to run? Did you try to restart the python interpreter?

**Comment by johnwheeler** [comment]
I am available to work interactively on this for the next hour or so

https://fathomless-citadel-83294.herokuapp.com/

John

**Comment by raddevon** [comment]
I was getting that when I started the skill rather that when I started the server. Thought for sure I had restarted the interpreter, but, after a restart just now, it's behaving. Sorry for the trouble. Thank you so much for the quick response!

**Comment by johnwheeler** [comment]
No worries at all. Thank you so much for trying my library.

It's important to know that the run mechanism has changed with Flask since version 0.11 which was released after the blog post.

The code still works as-is, but to get template reloading to work, you must do

```
export FLASK_APP=memory_game.py
export FLASK_DEBUG=1
flask run
```

Please see here:

http://flask.readthedocs.io/en/latest/quickstart/#a-minimal-application

**Comment by raddevon** [comment]
Thanks for the Flask tip, and thank you so much for building this. It's a lot of fun to work with!
