### ISSUE TITLE
samples/audio/playlist_demo fails with error after "start the playlist"

### ISSUE THREAD

**Issue by toxicated101** [johnwheeler/flask-ask#140]
The sample application fails with the following log when "Start the playlist" is called running with python3.4 on a raspberry pi

python3 playlist.py
 * Running on http://127.0.0.1:8082/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 734-353-854
127.0.0.1 - - [08/Jun/2017 11:46:19] "POST /tunes HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/flask_ask/core.py", line 594, in _flask_view_func
    result = self._map_intent_to_view_func(self.request.intent)()
  File "/home/pi/AlexaMusicSample/playlist.py", line 141, in start_playlist
    return audio(speech).play(stream_url)
  File "/usr/local/lib/python3.4/dist-packages/flask_ask/models.py", line 162, in play
    directive['audioItem'] = self._audio_item(stream_url=stream_url, offset=offset)
  File "/usr/local/lib/python3.4/dist-packages/flask_ask/models.py", line 216, in _audio_item
    push_stream(stream_cache, context['System']['user']['userId'], stream)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
TypeError: 'NoneType' object is not subscriptable

**Comment by voutilad** [comment]
Are you supplying a Context in your request? (See #126 for similar example.)

I've had a backlogged enhancement for catching a missing Context during Audio Directives and raising a more descriptive error.

**Comment by toxicated101** [comment]
I am testing using the service simulator within Amazon Developer Portal. I created the skill , pointed it at my server which is https , Audio Player is turned on in the Global  Fields.

Thanks

**Comment by voutilad** [comment]
It's a common issue that the Amazon Service Simulator doesn't send a Context and can't accurately test Audio Directives. You can try using something like ngrok + a physical Alexa device or something that simulates an Alexa device like https://echosim.io

**Comment by toxicated101** [comment]
Thanks, it works from an Amazon Echo Dot. It does stop after the 3rd song, even though it has a Next URL which appears to be valid. I will search the issues.


"Finished Audio stream for track 2"
"stepped queue forward"
{
  "Current Stream Status": {
    "offsetInMilliseconds": 0,
    "playerActivity": "FINISHED",
    "token": "933479d2-b794-46b1-9d8a-c99a0f9f71e2",
    "url": "https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3"
  },
  "Queue status": {
    "Current Position": 3,
    "Current URL": "https://archive.org/download/plpl011/plpl011_05-johnny_ripper-rain.mp3",
    "History": [
      "https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3",
      "https://archive.org/download/petescott20160927/20160927%20RC300-53-127.0bpm.mp3"
    ],
    "Next URL": "https://archive.org/download/piano_by_maxmsp/beats107.mp3",
    "Previous": "https://archive.org/download/petescott20160927/20160927%20RC300-53-127.0bpm.mp3"
  }
}
127.0.0.1 - - [08/Jun/2017 21:02:52] "POST /tunes HTTP/1.0" 400 -

**Comment by toxicated101** [comment]
Thanks, It works from an Amazon Echo Dot. It does stop after the 3rd Song even though it has a Next URL and appears to be valid:-

"Finished Audio stream for track 2"
"stepped queue forward"
{
  "Current Stream Status": {
    "offsetInMilliseconds": 0,
    "playerActivity": "FINISHED",
    "token": "933479d2-b794-46b1-9d8a-c99a0f9f71e2",
    "url": "https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3"
  },
  "Queue status": {
    "Current Position": 3,
    "Current URL": "https://archive.org/download/plpl011/plpl011_05-johnny_ripper-rain.mp3",
    "History": [
      "https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3",
      "https://archive.org/download/petescott20160927/20160927%20RC300-53-127.0bpm.mp3"
    ],
    "Next URL": "https://archive.org/download/piano_by_maxmsp/beats107.mp3",
    "Previous": "https://archive.org/download/petescott20160927/20160927%20RC300-53-127.0bpm.mp3"
  }
}
127.0.0.1 - - [08/Jun/2017 21:02:52] "POST /tunes HTTP/1.0" 400 -
