### ISSUE TITLE
UnicodeEncodeError when using non-ascii characters in speech response

### ISSUE THREAD

**Issue by joerg86** [johnwheeler/flask-ask#147]
If you use Alexa with the German language, not all responses will be in ASCII.

statement(u"Was kann ich für dich tun?") 
This will fail with a UnicodeEncodeError.

Traceback (most recent call last):
  File "/home/joerg/py/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/joerg/py/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/joerg/py/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/joerg/py/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/joerg/py/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/joerg/py/env/src/flask-ask/flask_ask/core.py", line 597, in _flask_view_func
    result = self._launch_view_func()
  File "alexa.py", line 11, in launch
    return statement(u"Hallo, ich bin die Pustel. Was kann ich für dich tun?")
  File "/home/joerg/py/env/src/flask-ask/flask_ask/models.py", line 115, in __init__
    super(statement, self).__init__(speech)
  File "/home/joerg/py/env/src/flask-ask/flask_ask/models.py", line 54, in __init__
    'outputSpeech': _output_speech(speech)
  File "/home/joerg/py/env/src/flask-ask/flask_ask/models.py", line 254, in _output_speech
    xmldoc = ElementTree.fromstring(speech)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1651, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 41: ordinal not in range(128)

The error happens when flask-ask tries to check if it is XML with etree. We need to catch UnicodeEncodeError here as well!

I have attached a patch that fixes the problem
[flask-ask-unicode.patch.txt](https://github.com/johnwheeler/flask-ask/files/1095927/flask-ask-unicode.patch.txt)

.

Thanks,

Jörg

**Comment by voutilad** [comment]
Thanks, @joerg86. I'll test the patch and confirm it works across Python versions.
