### ISSUE TITLE
How can handle event "ElementSelected" for echo show?

### ISSUE THREAD

**Issue by bj32161** [johnwheeler/flask-ask#177]
Hi,
I tried to looking for sample code to support event "ElementSelected" but no luck. This is error that I got from flash-ask when touch display template (ListTemplate2). Is there anyone can sharing the sample code?
Thank you.
Panya
====
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/wrappers.py", line 847, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/wrappers.py", line 57, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
=====

**Comment by johnddias** [comment]
This was my contribution so you can see how I used it in my solution [https://github.com/johnddias/vrobbie/blob/master/vrobbie.py](url) - care to share your code so I can see if I can help?

**Comment by bj32161** [comment]
hi johnddias
your link show error 404

**Comment by johnddias** [comment]
https://github.com/johnddias/vrobbie/blob/master/vrobbie.py

**Comment by nougad** [comment]
It does not work.

The commit 425e7e3e71315fc1edc304c7e353fd27cc9e226b was introducing the functionality:

```
+        elif request_type == 'Display.ElementSelected' and self._display_element_selected_func:
+            result = self._display_element_selected_func(
```

but the merge with 39bec79b905947c40843e9f0532f4be5431b101f was removing it again:

```
-        elif request_type == 'Display.ElementSelected' and self._display_element_selected_func:
-            result = self._display_element_selected_func()
```

the result it in the final merge ee71be2d40ebc77cb0ee6ab1413929c5354be409 this part is missing.

That results in the method gets never called and it always returns 400

**Comment by johnddias** [comment]
@johnwheeler how to fix?  Do I need to make another pull request to add this back in?
