### ISSUE TITLE
SSL Errors? Maybe related to validation?

### ISSUE THREAD

**Issue by stevenmcastano** [johnwheeler/flask-ask#19]
Everything was working fine when I went to sleep last night, I woke up this morning and wanted to keep doing a little work on my app, now all of a sudden I have some errors that I can't seem to track down They seem like they have to do with SSL and/or not being able to verify it. Any ideas? Anyone else seeing this?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 133, in _flask_view_func
    ask_payload = self._verified_request()
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 118, in _verified_request
    cert = verifier.load_certificate(cert_url)
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/verifier.py", line 20, in load_certificate
    cert = crypto.load_certificate(crypto.FILETYPE_PEM, cert_data)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 133, in _flask_view_func
    ask_payload = self._verified_request()
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 118, in _verified_request
    cert = verifier.load_certificate(cert_url)
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/verifier.py", line 20, in load_certificate
    cert = crypto.load_certificate(crypto.FILETYPE_PEM, cert_data)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
```

**Comment by johnwheeler** [comment]
Hi - I tried to reproduce this right now and couldn't. I did a fresh Flask-Ask install and recreated a hello world skill and it didn't report any errors. 

I'm guessing it's intermittent.

When Alexa sends a request to your skill, Flask-Ask grabs the certificate URL from an HTTP header

```
        cert_url = flask_request.headers['Signaturecertchainurl']
```

Since they have control over that URL, they might be using a CDN to gives clients different ones. I'm getting

```
https://s3.amazonaws.com/echo.api/echo-api-cert-3.pem
```

1. Can you reproduce this over and over?
1. What Operating System are you on

Thanks for trying Flask-Ask

**Comment by stevenmcastano** [comment]
I was able to produce it multiple times, and yes I got the same URL to the cert:

```
https://s3.amazonaws.com/echo.api/echo-api-cert-3.pem
```

As it turns out... I was "half right", it is a problem verifying the SSL cert. For some reason my own internal DNS server was telling me the host `s3.amazonaws.com` didn't exist so the verification process wasn't able to get the cert contents.

I'm still not sure why my DNS server doesn't want to work, but I change my systems DNS to `8.8.8.8` (Google's public DNS server) and the problem went away!

I guess you can mark this one closed as it seems to be a network issue in my environment or some sort of DNS issue reaching S3. It's good to know thought, for people that get that error message to try doing a `curl` from the host running the code to the certificate URL and make sure you get a valid pem certificate back.

And no no, thank YOU for writing Flask-Ask, I love it so far... I've got my Echo basically controlling my entire house. Lights, music, TV's, checking voicemail, sending texts for me, even reading emails if I need it to.

GREAT project!!! Keep up the good work and if there's any way to me to help/contribute just tell me how!

**Comment by johnwheeler** [comment]
That's wonderful feedback, and I'm glad to hear you like Flask-Ask! Also, thanks for being a watcher. You'll see a few things come down the pipe soon. Any feedback you have on them is most, most welcome.

1. Documentation to deploy to Lambda using Zappa. Zappa makes deploying to Lambda literally one command: `zappa deploy production`
1. State Machine. It's currently in another branch being worked out. It makes writing complex conversational apps way easier.

Please join us on Gitter https://gitter.im/johnwheeler/flask-ask. Not much activity yet, but just having heads in there (even inactive ones) is super helpful.

Glad you got the issue resolved, but it sounds like it was a head scratcher for sure!
