### ISSUE TITLE
Demo blueprint project does not work

### ISSUE THREAD

**Issue by nbars** [johnwheeler/flask-ask#199]
Hi,

I'm trying to setup you're blueprint sample project, but it doesn't work.
I only changed the API path from ```ask``` to ```ask_api``` (of the blueprint). Everything else is left as it is in the master branch of ```flask-ask```.

```
Flask==0.12.1
Flask-Ask==0.9.7
```

If I send a (random) request with the Amazon test service to my service, I get the following error:
```
 * Serving Flask app "demo"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2017-10-22 00:56:09,991] ERROR in app: Exception on /ask_api [POST]
Traceback (most recent call last):
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask_ask/core.py", line 646, in _flask_view_func
    self._update_stream()
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask_ask/core.py", line 618, in _update_stream
    dbgdump(current_stream.__dict__)
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/nils/git/podcatcher/podcatcher-env/lib/python3.6/site-packages/flask_ask/core.py", line 51, in <lambda>
    current_stream = LocalProxy(lambda: find_ask().current_stream)
AttributeError: 'NoneType' object has no attribute 'current_stream'
```
I would appriciate any help, thanks!

**Comment by nbars** [comment]
I don't know why, but reinstalling ```flask-ask``` solved this issue.
