### ISSUE TITLE
Issue with pyOpenSSL

### ISSUE THREAD

**Issue by chishaku** [johnwheeler/flask-ask#39]
I set up the demo memory game which I have running on Ubuntu 16.04.  I've configured an ngrok https endpoint in the Amazon portal.

I sent a test request from the Amazon portal and I'm getting a 500 server error which might have something to do with pyOpenSSL certificate handling but I'm not at all sure.

Here is the Flask traceback:

```
127.0.0.1 - - [01/Nov/2016 19:15:40] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/midp/env/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/midp/env/lib/python2.7/site-packages/flask_ask/core.py", line 400, in _flask_view_func
    ask_payload = self._alexa_request(verify=self.ask_verify_requests)
  File "/home/midp/env/lib/python2.7/site-packages/flask_ask/core.py", line 373, in _alexa_request
    cert = verifier.load_certificate(cert_url)
  File "/home/midp/env/lib/python2.7/site-packages/flask_ask/verifier.py", line 21, in load_certificate
    if not _valid_certificate(cert):
  File "/home/midp/env/lib/python2.7/site-packages/flask_ask/verifier.py", line 63, in _valid_certificate
    value = str(extension)
  File "/home/midp/env/lib/python2.7/site-packages/OpenSSL/crypto.py", line 707, in __str__
    if _lib.NID_subject_alt_name == self._nid:
  File "/home/midp/env/lib/python2.7/site-packages/OpenSSL/crypto.py", line 659, in _nid
    return _lib.OBJ_obj2nid(self._extension.object)
AttributeError: '_cffi_backend.CDataGCP' object has no attribute 'object'
```

**Comment by chishaku** [comment]
`pip install -U pyopenssl` fixed the issue.  

Sweet project, @johnwheeler.  Thank you!
