### ISSUE TITLE
on_playback_nearly_finished gives error

### ISSUE THREAD

**Issue by foxy82** [johnwheeler/flask-ask#40]
When running:

@ask.on_playback_nearly_finished(mapping={'offset': 'offsetInMilliseconds', 'stream_location': 'url', 'stream_number$
def play_next_stream(offset, stream_location, token):
  global nextTrack
  global tracks
  logger.info("offsset [{}] token[{}] stream_location[{}]".format(offset, token, stream_location))
  logger.info("Next track {} Total Tracks {}".format(nextTrack, len(tracks)))

  my_logger.info('Nearly finished')
  id = tracks[nextTrack]
  nextTrack += 1
  my_next_song = get_stream_url(id)
  audio('').enqueue(my_next_song)

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 425, in _flask_view_func
    result = self._map_player_request_to_func(self.request)()
  File "gmusic_player.py", line 196, in play_next_stream
    audio('').enqueue(my_next_song)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 636, in enqueue
    audio_item['stream']['expectedPreviousToken'] = audio.prev_stream.token
AttributeError: type object 'audio' has no attribute 'prev_stream'

**Comment by treethought** [comment]
Just pushed a commit that should fix this.
The example usages for the playback callback funcs have been updated to hopefully be a little more clear. There is also now an example skill showing one way to play through a playlist.

One thing to note is that the PlayBackNearlyFinished Request is usually sent almost immediately after you send a PlayDirective. The name of the request is a little deceptive, but it just means Alexa will allow a new stream to be enqueued.

These callbacks can accept any top-level parameters of the request body, even if not mapped. Although offset is mapped by default to offsetInMilliSeconds for convenience.
The request_body never includes a url however, so that would need be accessed through the current_stream local's 'url' attribute.

You will see in the playlist example a QueueManager class. Something like this is required to keep track of queue order and which url is currently being streamed. But from your examples, it seems like you have come up with something similar.

I'll try to incorporate some type of QueueManager into the flask-ask locals if @johnwheeler thinks that would be a good idea, so that managing a queue can work out of the box.

**Comment by johnwheeler** [comment]
@treethought Go for it! You're doing great as the lead on the streaming audio

**Comment by treethought** [comment]
Sounds good! Thanks, John.

**Comment by foxy82** [comment]
Hey just tried this sample it plays the first sound and then errors in playback_nearly_finished and doesn't play anymore. any idea what I'm doing wrong?

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 425, in _flask_view_func
    result = self._map_player_request_to_func(self.request)()
  File "/home/neil/alexa-gmusic/playlist.py", line 202, in started
    _infodump('STARTED Audio stream from {}'.format(current_stream.url))
AttributeError: 'LocalStack' object has no attribute 'url'
"Alexa is now ready for a Next or Previous Intent"
127.0.0.1 - - [09/Nov/2016 19:37:27] "POST / HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 425, in _flask_view_func
    result = self._map_player_request_to_func(self.request)()
  File "/home/neil/alexa-gmusic/playlist.py", line 153, in nearly_finished
    return audio().enqueue(next_stream)
TypeError: __init__() missing 1 required positional argument: 'speech'
127.0.0.1 - - [09/Nov/2016 19:37:29] "POST / HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 425, in _flask_view_func
    result = self._map_player_request_to_func(self.request)()
  File "/home/neil/alexa-gmusic/playlist.py", line 160, in play_back_finished
    _infodump('FINISHED Audio stream from {}'.format(current_stream.url))
AttributeError: 'LocalStack' object has no attribute 'url'

**Comment by foxy82** [comment]
Never mind was still hitting the old 0.8.0 code in my import... works at first try.
