### ISSUE TITLE
Getting 'HTTP_SIGNATURECERTCHAINURL' when running flask_ask behind a proxy

### ISSUE THREAD

**Issue by IwanLD** [johnwheeler/flask-ask#43]
Hey, I tried running flask-ask behind the [lambda-proxy by Matt Kruse](https://forums.developer.amazon.com/questions/8155/how-to-use-aws-lambda-as-a-proxy-for-non-ssl-serve.html) and get the attached error. It seems to be that the JAVA ASK SDK  has a flag to turn off the key check. Maybe a cool feature for flask-ask as well?

```
54.162.204.77 - - [04/Nov/2016 18:46:32] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 400, in _flask_view_func
    ask_payload = self._alexa_request(verify=self.ask_verify_requests)
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 369, in _alexa_request
    cert_url = flask_request.headers['Signaturecertchainurl']
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 1312, in __getitem__
    return _unicodify_header_value(self.environ['HTTP_' + key])
KeyError: 'HTTP_SIGNATURECERTCHAINURL'
```

**Comment by foxy82** [comment]
Is the second config option on this page what you are asking for? https://alexatutorial.com/flask-ask/configuration.html

I'm running flask-ask behind haproxy fine.

**Comment by IwanLD** [comment]
Thanks, that should solve it. Could you please give me a hint on setting them? Wasn't obvious from the docs for me.

**Comment by digiltd** [comment]
In case others stumble upon this issue (as I did) the syntax to set config (source #37)  

`app.config['ASK_VERIFY_REQUESTS'] = False`

where `app` = your appname
