### ISSUE TITLE
Playlist sample doesn't enqueue next song

### ISSUE THREAD

**Issue by foxy82** [johnwheeler/flask-ask#58]
Hi,

I think this might be a change amazon end... my own implementation of a playlist has stopped moving to the next song... so I tried the sample one and that also has stopped moving to the next song.
Changing logging to debug when we het a PlayBackNearlyFininshed and call enqueue it is returning:

  "request": {
    "cause": {
      "requestId": "amzn1.echo-api.request."
    },
    "error": {
      "message": "The following directives are not supported: Response may not contain an outputSpeech",
      "type": "INVALID_RESPONSE"
    },
    "locale": "en-GB",
    "requestId": "amzn1.echo-api.request",
    "timestamp": "2016-12-15T15:43:12Z",
    "type": "System.ExceptionEncountered"
  },
  "version": "1.0"

**Comment by mcverna** [comment]
I'm seeing the same behavior in the sample app and getting the same error that you posted.  It plays a single song then stops. Also positional offset is not getting updated in on_playback_stopped and on_playback_started.  Seeking is problematic as well.

**Comment by treethought** [comment]
Just pushed a commit to fix the enqueuing of new streams.

This also makes Next and Previous intents work again, but every once in a while I get a 400 bad request when using ngrok. I'm not sure if that is due to the audio request/responses or an issue with verifying the alexa request more generally.

@mcverna This doesn't fix the offset issue, still working on that. And do you mean seeking as in stepping through different songs or within one song's length?
When moving to the next or previous song you need to wait to send the intent until Alexa is ready to accept it. You can monitor when its ready with the on_playback_nearly_finished decorator.

**Comment by mcverna** [comment]
Great I'll check it out.  Thanks.  I'm referring to seeking within a file by calling play with a non zero offset.  I was also wanting to get the offset that is supposed to be provided with the on stop function so I can subsequently call play at a later time with that offset.   But offset via the different on handlers are always showing as none.

**Comment by mcverna** [comment]
The fix didn't work for me.  Looks like we need the token value to be present for the enqueue operation as well.  I can play the next song just fine by saying next without enqueue.

**Comment by foxy82** [comment]
Also with the playlist demo I get the following error...

127.0.0.1 - - [20/Dec/2016 06:42:53] "POST / HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 516, in _flask_view_func
    result = self._map_intent_to_view_func(self.request.intent)()
  File "/usr/local/lib/python3.5/dist-packages/flask_ask/core.py", line 530, in _map_intent_to_view_func
    view_func = self._intent_view_funcs[intent.name]

**Comment by foxy82** [comment]
The new code works for me as well for the queuing up the next song... thanks... just in time for Christmas :)

**Comment by ohabash** [comment]
hmm this might be a newb question but how do i know if i have the new code? After starting the playlist, one audio plays and the below is put putted (using ngrok)

   ```
"STARTED Audio Stream at None ms"

"STARTED Audio stream from https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3"


127.0.0.1 - - [28/Dec/2016 10:31:48] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask_ask/core.py", line 518, in _flask_view_func
    result = self._map_player_request_to_func(self.request.type)()
  File "/Users/ohabash/Dropbox/python/flask-ask/playlist/playlist.py", line 199, in started
    _infodump({'queue': queue.status})
  File "/Users/ohabash/Dropbox/python/flask-ask/playlist/playlist.py", line 50, in status
    'Next URL': self.up_next,
  File "/Users/ohabash/Dropbox/python/flask-ask/playlist/playlist.py", line 59, in up_next
    qcopy = self._queued.copy()
AttributeError: 'collections.deque' object has no attribute 'copy'


127.0.0.1 - - [28/Dec/2016 10:31:49] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask_ask/core.py", line 518, in _flask_view_func
    result = self._map_player_request_to_func(self.request.type)()
  File "/Users/ohabash/Dropbox/python/flask-ask/playlist/playlist.py", line 146, in nearly_finished
    if queue.up_next:
  File "/Users/ohabash/Dropbox/python/flask-ask/playlist/playlist.py", line 59, in up_next
    qcopy = self._queued.copy()
AttributeError: 'collections.deque' object has no attribute 'copy'
"FINISHED Audio stream from https://archive.org/download/mailboxbadgerdrumsamplesvolume2/Ringing.mp3"

127.0.0.1 - - [28/Dec/2016 10:31:51] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ohabash/Dropbox/python/flask-ask/loteria/loteria_dev/lib/python2.7/site-packages/flask_ask/core.py", line 518, in _flask_view_func
    result = self._map_player_request_to_func(self.request.type)()
  File "/Users/ohabash/Dropbox/python/flask-ask/playlist/playlist.py", line 157, in play_back_finished
    if queue.up_next:
  File "/Users/ohabash/Dropbox/python/flask-ask/playlist/playlist.py", line 59, in up_next
    qcopy = self._queued.copy()
AttributeError: 'collections.deque' object has no attribute 'copy'

```

**Comment by foxy82** [comment]
That wasn't the bug so looks like you've got a different problem. It works
ok for me using python 3.
