### ISSUE TITLE
Python 2.7.13 issue

### ISSUE THREAD

**Issue by strunker** [johnwheeler/flask-ask#67]
When I try to launch my code I receive the below error. Not too sure what to make of that?

Traceback (most recent call last):
  File "C:\Python27\Echo\Control.py", line 7, in <module>
    from flask_ask import Ask, statement, question, session
  File "C:\Python27\lib\site-packages\flask_ask\__init__.py", line 8, in <module>
    from .core import (
  File "C:\Python27\lib\site-packages\flask_ask\core.py", line 11, in <module>
    from . import verifier
  File "C:\Python27\lib\site-packages\flask_ask\verifier.py", line 8, in <module>
    from OpenSSL import crypto
  File "C:\Python27\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Python27\lib\site-packages\OpenSSL\rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "C:\Python27\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by strunker** [comment]
solved this.. its due to 32 bit 2.7.13 being installed when I had 64bit 2.7.11.

Once I installed 64bit 2.7.13 all was well.

**Comment by bogdancraciun** [comment]
I get a similar problem on a Raspberry Pi, latest Raspbian with Python 2.7.9

```
pi@raspberrypi:~/scripts $ python --version
Python 2.7.9
pi@raspberrypi:~/scripts $ uname -a
Linux raspberrypi 4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l GNU/Linux
pi@raspberrypi:~/scripts $ python memory_game.py
Traceback (most recent call last):
  File "memory_game.py", line 7, in <module>
    from flask_ask import Ask, statement, question, session
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/__init__.py", line 9, in <module>
    from .core import (
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/core.py", line 12, in <module>
    from . import verifier, logger
  File "/usr/local/lib/python2.7/dist-packages/flask_ask/verifier.py", line 8, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
```
