### ISSUE TITLE
on close session i always get this error, NoneType object is not iterable

### ISSUE THREAD

**Issue by molavy** [johnwheeler/flask-ask#94]
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/venv/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/venv/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/user/venv/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/venv/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/venv/lib/python3.4/site-packages/flask_ask/core.py", line 541, in _flask_view_func
    self._update_stream()
  File "/home/user/venv/lib/python3.4/site-packages/flask_ask/core.py", line 510, in _update_stream
    fresh_stream.__dict__.update(self._from_context())
TypeError: 'NoneType' object is not iterable

 it is not related to my code , i don't see any line that come into my code

**Comment by molavy** [comment]
i can't find where this issue first submitted, please refer first issue when mark as duplicate, thanks

**Comment by molavy** [comment]
i found this here
https://github.com/johnwheeler/flask-ask/issues/88
but i offer install version 8.2
but i latest version:
Successfully installed flask-ask-0.8.6

**Comment by johnwheeler** [comment]
flask-ask-0.8.7 has been pushed to PyPi. Please upgrade
